apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "konga.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{- if .Values.config }}
  {{- $db_adapter := (default "localDiskDb" .Values.config.db_adapter) }}
  {{- if ne $db_adapter "localDiskDb" }}
  {{- if not .Values.config.db_uri }}
  DB_PASSWORD: {{ .Values.config.db_password }}
  {{- end }}
  {{- end }}
  {{- if .Values.config.token_secret }}
  TOKEN_SECRET: {{ .Values.config.token_secret }}
  {{- end }}
  {{- end }}
